"""2nd migration

Revision ID: 5d5b1e854a0d
Revises: 42889b7bed1a
Create Date: 2020-11-16 15:21:32.403130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5b1e854a0d'
down_revision = '42889b7bed1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'journal', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_column('journal', 'user_id')
    # ### end Alembic commands ###
